authorizer:
  resultTtlInSeconds: 0 # It causes weird issues if not 0
  name: authorizer
  type: request

customDomain:
  domainName: staging.api.example.com
  certificateName: example.com
  stage: ${opt:stage}
  createRoute53Record: true
  basePath: ''

plugins:
  - serverless-domain-manager
